development:
  adapter: postgresql
  encoding: unicode
  database: databasename
  pool: 5
  username: think
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: testdatabasename
  pool: 5
  username: think
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: testdatabasename
  pool: 5
  username: think
  password:
           
